import { DashboardLayout } from "@/components/layout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useParams, Link } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { Loader2, ArrowLeft, Copy, Check, FileText, Mail, Clock, Eye, BookOpen, ClipboardList } from "lucide-react";
import { format } from "date-fns";
import { useState } from "react";

interface PatientSummary {
  patientEmail: string;
  generatedAt: string;
  clinicianName: string;
  stats: {
    totalEmailsSent: number;
    totalContentSent: number;
    contentViewed: number;
    engagementRate: number;
    totalReadingTimeMinutes: number;
    assessmentsSent: number;
    assessmentsCompleted: number;
  };
  contentEngagement: {
    contentTitle: string;
    tags: string[];
    sentAt: string;
    viewedAt: string | null;
    timeSpentSeconds: number;
  }[];
  emailHistory: {
    date: string;
    subject: string;
    type: string;
    status: string;
    contentCount: number;
  }[];
  assessmentHistory: {
    sentAt: string;
    status: string;
    completedAt: string | null;
  }[];
}

async function fetchPatientSummary(email: string): Promise<PatientSummary> {
  const res = await fetch(`/api/patient-summary/${encodeURIComponent(email)}`, {
    credentials: "include",
  });
  if (!res.ok) throw new Error("Failed to fetch patient summary");
  return res.json();
}

function formatTime(seconds: number): string {
  if (seconds < 60) return `${seconds} seconds`;
  const mins = Math.floor(seconds / 60);
  if (mins < 60) return `${mins} minute${mins !== 1 ? 's' : ''}`;
  const hours = Math.floor(mins / 60);
  const remainingMins = mins % 60;
  return `${hours} hour${hours !== 1 ? 's' : ''} ${remainingMins} minute${remainingMins !== 1 ? 's' : ''}`;
}

function generateEMRNote(summary: PatientSummary): string {
  const today = format(new Date(), "MM/dd/yyyy");
  
  let note = `PATIENT EDUCATION SUMMARY
Generated: ${today}
Patient: ${summary.patientEmail}
Provider: ${summary.clinicianName}

ENGAGEMENT OVERVIEW:
- Educational materials sent: ${summary.stats.totalContentSent} items across ${summary.stats.totalEmailsSent} email(s)
- Materials reviewed by patient: ${summary.stats.contentViewed} items (${summary.stats.engagementRate}% engagement rate)
- Total reading time: ${summary.stats.totalReadingTimeMinutes} minutes
- Assessments completed: ${summary.stats.assessmentsCompleted} of ${summary.stats.assessmentsSent} sent

`;

  if (summary.contentEngagement.length > 0) {
    note += `CONTENT ENGAGEMENT DETAIL:\n`;
    summary.contentEngagement.forEach(item => {
      const status = item.viewedAt ? `Viewed (${formatTime(item.timeSpentSeconds)})` : 'Not viewed';
      note += `- ${item.contentTitle}: ${status}\n`;
      if (item.tags.length > 0) {
        note += `  Topics: ${item.tags.join(', ')}\n`;
      }
    });
    note += '\n';
  }

  if (summary.assessmentHistory.length > 0) {
    note += `ASSESSMENT HISTORY:\n`;
    summary.assessmentHistory.forEach(item => {
      const sentDate = format(new Date(item.sentAt), "MM/dd/yyyy");
      const status = item.status === 'completed' 
        ? `Completed ${item.completedAt ? format(new Date(item.completedAt), "MM/dd/yyyy") : ''}`
        : item.status.charAt(0).toUpperCase() + item.status.slice(1);
      note += `- Sent: ${sentDate} | Status: ${status}\n`;
    });
    note += '\n';
  }

  note += `---
This summary was generated by RehabPilot patient education platform.`;

  return note;
}

export default function PatientSummaryPage() {
  const params = useParams<{ email: string }>();
  const patientEmail = decodeURIComponent(params.email || "");
  const [copied, setCopied] = useState(false);

  const { data: summary, isLoading, error } = useQuery({
    queryKey: ["patient-summary", patientEmail],
    queryFn: () => fetchPatientSummary(patientEmail),
    enabled: !!patientEmail,
  });

  const handleCopy = () => {
    if (!summary) return;
    const note = generateEMRNote(summary);
    navigator.clipboard.writeText(note);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (isLoading) {
    return (
      <DashboardLayout>
        <div className="flex items-center justify-center min-h-[400px]">
          <Loader2 className="w-8 h-8 animate-spin text-primary" />
        </div>
      </DashboardLayout>
    );
  }

  if (error || !summary) {
    return (
      <DashboardLayout>
        <div className="space-y-6">
          <Link href="/history">
            <Button variant="ghost" size="sm">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to History
            </Button>
          </Link>
          <Card>
            <CardContent className="pt-6 text-center">
              <p className="text-muted-foreground">No data found for this patient.</p>
            </CardContent>
          </Card>
        </div>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div>
            <Link href="/history">
              <Button variant="ghost" size="sm" className="mb-2">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to History
              </Button>
            </Link>
            <h1 className="text-3xl font-serif font-bold">Patient Summary</h1>
            <p className="text-muted-foreground">{summary.patientEmail}</p>
          </div>
          <Button onClick={handleCopy} data-testid="button-copy-emr">
            {copied ? (
              <>
                <Check className="w-4 h-4 mr-2" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4 mr-2" />
                Copy EMR Note
              </>
            )}
          </Button>
        </div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Content Sent</CardTitle>
              <Mail className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{summary.stats.totalContentSent}</div>
              <p className="text-xs text-muted-foreground">
                Across {summary.stats.totalEmailsSent} email{summary.stats.totalEmailsSent !== 1 ? 's' : ''}
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Content Viewed</CardTitle>
              <Eye className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{summary.stats.contentViewed}</div>
              <p className="text-xs text-muted-foreground">
                {summary.stats.engagementRate}% engagement rate
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Reading Time</CardTitle>
              <Clock className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{summary.stats.totalReadingTimeMinutes}m</div>
              <p className="text-xs text-muted-foreground">Total time spent reading</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Assessments</CardTitle>
              <ClipboardList className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                {summary.stats.assessmentsCompleted}/{summary.stats.assessmentsSent}
              </div>
              <p className="text-xs text-muted-foreground">Completed</p>
            </CardContent>
          </Card>
        </div>

        <div className="grid lg:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BookOpen className="w-5 h-5" />
                Content Engagement
              </CardTitle>
              <CardDescription>How this patient interacted with educational content</CardDescription>
            </CardHeader>
            <CardContent>
              {summary.contentEngagement.length > 0 ? (
                <div className="space-y-4">
                  {summary.contentEngagement.map((item, i) => (
                    <div key={i} className="flex items-start gap-4 pb-4 border-b last:border-0 last:pb-0 border-border/50">
                      <div className={`w-2 h-2 mt-2 rounded-full ${item.viewedAt ? 'bg-green-500' : 'bg-gray-300'}`} />
                      <div className="flex-1 min-w-0">
                        <div className="font-medium text-sm">{item.contentTitle}</div>
                        {item.tags.length > 0 && (
                          <div className="flex flex-wrap gap-1 mt-1">
                            {item.tags.slice(0, 3).map((tag, j) => (
                              <Badge key={j} variant="secondary" className="text-xs">
                                {tag}
                              </Badge>
                            ))}
                          </div>
                        )}
                        <div className="flex items-center gap-2 mt-2">
                          {item.viewedAt ? (
                            <>
                              <Badge variant="outline" className="text-green-600 border-green-200 bg-green-50 text-xs">
                                <Eye className="w-3 h-3 mr-1" /> Viewed
                              </Badge>
                              <span className="text-xs text-muted-foreground">
                                {formatTime(item.timeSpentSeconds)}
                              </span>
                            </>
                          ) : (
                            <Badge variant="secondary" className="text-xs">Not viewed</Badge>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-muted-foreground text-sm text-center py-4">No content sent yet</p>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="w-5 h-5" />
                EMR Documentation
              </CardTitle>
              <CardDescription>Copy this note into your electronic medical record</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="bg-muted/50 rounded-lg p-4 font-mono text-xs whitespace-pre-wrap max-h-[400px] overflow-y-auto">
                {generateEMRNote(summary)}
              </div>
              <Button onClick={handleCopy} className="w-full mt-4" variant="outline">
                {copied ? (
                  <>
                    <Check className="w-4 h-4 mr-2" />
                    Copied to Clipboard!
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4 mr-2" />
                    Copy to Clipboard
                  </>
                )}
              </Button>
            </CardContent>
          </Card>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Email History</CardTitle>
            <CardDescription>All communications sent to this patient</CardDescription>
          </CardHeader>
          <CardContent>
            {summary.emailHistory.length > 0 ? (
              <div className="space-y-3">
                {summary.emailHistory.map((email, i) => (
                  <div key={i} className="flex items-center justify-between p-3 bg-muted/30 rounded-lg">
                    <div className="flex items-center gap-3">
                      <Mail className="w-4 h-4 text-muted-foreground" />
                      <div>
                        <div className="font-medium text-sm">{email.subject}</div>
                        <div className="text-xs text-muted-foreground">
                          {format(new Date(email.date), "MMM d, yyyy 'at' h:mm a")} | {email.contentCount} item{email.contentCount !== 1 ? 's' : ''}
                        </div>
                      </div>
                    </div>
                    <Badge 
                      variant={email.status === 'clicked' ? 'default' : 'secondary'}
                      className={email.status === 'clicked' ? 'bg-green-100 text-green-700' : ''}
                    >
                      {email.status}
                    </Badge>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-muted-foreground text-sm text-center py-4">No emails sent yet</p>
            )}
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
}
